### ISSUE TITLE
Can't init guillotine with a scale

### ISSUE THREAD

**Issue by Evan-Peuvergne** [matiasgagliano/guillotine#11]
Hi,

Fist of all, I would like to congratulate you for your work with guillotine : this is just an amazing plugin, so useful.
I just met one problem : I don't manage to init the guillotine with a different scale while I manage to set a default position or orientation (with x, y, or angle keys in init object but "scale" seems to not work).

First, is it simply possible to set this param ? And then, how do I have to set it ?
Thank you very much for you answers ;)

**Comment by benjaminprojas** [comment]
@matiasgagliano I do believe that this is an issue.  When setting both scale AND angle, it first scales the image, to the correct scale, but then when it sets the angle, it changes the scale.  A workaround by editing the _init and _rotate functions like so:

```javascript
Guillotine.prototype._init = function() {
  var angle, o, scale;
  o = this.op.init;
  if ((scale = parseFloat(o.scale))) {
    this._zoom(scale);
  }
  if ((angle = parseInt(o.angle))) {
    this._rotate(angle, scale); // sending in the scale here to the rotate function
  }
  return this._offset(parseInt(o.x) / this.op.width || 0, parseInt(o.y) / this.op.height || 0);
};
```
...
```javascript
Guillotine.prototype._rotate = function(angle, scale) { // passing in scale here
  // removed the code here for brevity
  if(scale) { // if a scale is passed, run the _zoom function again to reset the scale
    this._zoom(scale);
  }
  return this.data.angle = this.angle;
};
```

This worked perfectly for me, but obviously require editing the file itself... Is this something that could be implemented?

**Comment by matiasgagliano** [comment]
@benjaminprojas what version of Guillotine are you using? What are the dimensions of the image and the window (guillotine width and height)? What are you passing to the `init` param?

A similar problem was reported in #17 and was fixed with [this commit](https://github.com/matiasgagliano/guillotine/commit/4d393f508dea0df25d481490910b07fbf13e2481).

The problem was that `rotate` scales images if after rotation any of the dimensions turns out to be smaller than the window (or guillotine) to fit it. So, as scale was applied afterwards, those cases ended being over scaled. But that was fixed, so let me know what's your particular case.

**Comment by benjaminprojas** [comment]
@matiasgagliano I am using Guillotine 1.3.0.
```javascript
Width: 130,
Height: 182
```
```javascript
init: {angle: 270, scale: 0.0628930817610063, x: 0, y: 0}
```
When I run getData, this is what I get:
```javascript
getData {angle: 270, h: 182, scale: 0.08805031446540881, w: 130, x: 0, y: 0}
```
I think I actually have a better grasp on what the issue actually is, and I will try to explain it here:

When an image is uploaded in landscape mode, and then rotated to be portrait, the initial scaling doesn't work because the ratio is too high for the dimensions of my window (130x182). Because of this it doesn't zoom to the correct position that I had set with init.  A workaround is to check if the getData['scale'] is the same as the passed in scale after it has been rotated.  If not, scale again...

Here is what I am using to make this work: 

```javascript
var setData = function(picture, gllt, data) {
  picture.guillotine('fit').guillotine('center');
  var current = gllt.getData(),
    scale = (data.scale !== 'undefined') ? data.scale / current.scale : false,
    angle = (data.angle !== 'undefined') ? data.angle - current.angle : false,
    left  = (data.x !== 'undefined') ? data.x / current.w : 0,
    top   = (data.y !== 'undefined') ? data.y / current.h : 0;

  if(scale) {
    gllt._zoom(scale);
  }

  if(angle) {
    gllt._rotate(angle);
  }
  // if the scale doesn't match, zoom again
  if(scale && gllt.getData()['scale'].toFixed(4) !== data.scale.toFixed(4)) {
    gllt._zoom(scale);
  }

  gllt._offset(left, top);

  // Trigger event and callback
  gllt._trigger('setData');
}
var gllt = picture.guillotine('instance');
setData(picture, gllt, init);
```

**Comment by matiasgagliano** [comment]
@benjaminprojas what are the real dimensions of the image?

Zoom is applied before rotation and it doesn't depend on the ratio. So, if the dimensions of the image in portrait mode, after being scaled, are both bigger than the ones of the window then rotation shouldn't mess with the scale.

Are you sure that a scale of `0.0628930817610063` is big enough to fit the image in portrait mode inside the window?

Keep in mind that `_zoom` is **relative**, it applies the scale over the current size, it's not an absolute measure over the original size of the image. The code you posted won't behave as expected.

Post the code that you use to initialize guillotine and the dimensions of the image you are using, if everything is ok I'll run some tests and look deeper into the code to see what's going on.
