### ISSUE TITLE
Doesn't seem to work on iPhone in either Safari nor Chrome

### ISSUE THREAD

**Issue by loevgaard** [matiasgagliano/guillotine#15]
I have tried your demo on iPhone in both Safari and Chrome. In Chrome the picture doesn't display and in Safari I can't zoom, rotate or anything.

**Comment by matiasgagliano** [comment]
I've pushed a more robust approach to the *issue-15* branch, I hope it fixes the issue with Chrome. 

I guess that Chrome for iPhone and iPad supports neither *img.naturalWidth* and *img.naturalHeight* nor *img.width* and *img.height*.

According to [this](//developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) desktop support for *natural* properties is quite good, but probably mobile not so much. It seems unthinkable that the same browser wouldn't support the same properties across devises, there's something weird cooking here.

@Sedins, I haven't been able to reproduce the issue about the plugin not initializing, could you elaborate more about it? Does the image load?

The dragging issue on IE11 most likely relates to pointer events, I'll see into it after working this out. 

Thanks for contributing!

**Comment by Sedins** [comment]
No problem. Here goes about uninitialized cropper:

The image does load but is displayed as a normal image. It's not possible to drag it just as if the cropper hasn't been initialized. All values (x/y/width/height/scale/angle) are empty as well. Refreshing the page one or two times use to resolve the problem, but that is not pretty (most users may not even do it)...

It reproduces every 2-3 refresh in IE11 with the same result on both the official and another IIS running the demo site. Clients used were a Windows 7 in Hyper-VM and a stand-alone Windows 8.1 desktop machine. I very rarely have seen the same problem in Chrome.

Console is free from errors, but displays this warning in Chrome (in IE it's empty): The key "target-densitydpi" is not supported. Pretty sure that it's not related, but mentioning it anyway.

Related note: Have seen the same behavior in another cropbox as well. The problem was that the cropbox initialized before the image was loaded. They solved it by creating an onload event on the plugin where it was possible to trigger to initialization routine from.

Attached is an image showing me dragging the image (which only moves the whole image, not dragging in within the crop container) and empty x/y-values.

![cropper_empty_values](https://cloud.githubusercontent.com/assets/6508927/5600242/31246adc-92d6-11e4-90f5-926cf68cee6c.png)

**Comment by Sedins** [comment]
Current issue-15 branch tests:

iPhone 6+ running iOS 8 using Safari works!
iPhone 6+ running iOS 8 using Chrome works!
Nexus 5 running Android 5.0 using Chrome works.
PC running Windows 7 and 8.1 using Chrome 39 works.
PC running Windows 2008 R2 using IE 10 works.

**Comment by Sedins** [comment]
Current issue-15 branch tests:

iPhone 5 running iOS 7 using Safari works!
iPhone 5 running iOS 7 using Chrome works!

**Comment by matiasgagliano** [comment]
Thank you very much @Sedins.

I'll push this browser compatibility fixes to master with a few minor improvements and wrap the 1.3 version to avoid delaying it further.

After that it'd be nice if you and/or @xims could update the wiki's [support page] (//github.com/matiasgagliano/guillotine/wiki/Support) so you're properly credited for your contributions.

I've confirmed that the dragging issue on IE11 is due to pointer events. They trigger mouse events anyway so I'll drop support for pointer events for now.

Given that the initialization issue happens mostly on IE and that it isn't critical I'll leave it for the next mayor release. Many reported troubles initializing the plugin because they didn't take into account that the image needs to be completely loaded before running the plugin, so I'm planning to re design some sections to ease this out, possibly this will fix the initialization issue too.

**Comment by Sedins** [comment]
Sounds great! Also dropping support for pointer events as a workaround for now would be nice to get the plugin working across all browsers.

Thanks a lot for this plugin. Looking forward to the 1.3 release. Really no problem to help out with the testing part a bit as we all benefit from it. Always nice to hear that it's appreciated though. I've updated the support page with new entries which has been tested btw.
