### ISSUE TITLE
Full Image and Centered (Not fit)

### ISSUE THREAD

**Issue by gshaxor** [matiasgagliano/guillotine#37]
I'm trying to put guillotine allows a complete picture, but there is always aligned not centered :( . How I can do to stay centered? And not to allow zoom to more than 100% of the image?

Actually (good but not centered):
![screenshot_1](https://cloud.githubusercontent.com/assets/1691623/8151472/bcf87100-12e4-11e5-85f4-5448a94ab2c2.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/1691623/8151473/bed0f376-12e4-11e5-9cb3-caedd1665ed8.png)

Regards!

**Comment by matiasgagliano** [comment]
@gshaxor please post the code that initializes the plugin and any other code that might be relevant to figure out what's not working for you.

**Comment by gshaxor** [comment]
I only change this:

Guillotine.prototype._zoom = function(factor) {
      var h, left, top, w;
      if (factor <= 0 || factor === 1) {
        return;
      }
      w = this.width;
      h = this.height;
      if (w * factor > 1 && h * factor > 1) {
        this.width *= factor;
        this.height *= factor;
        this.canvas.style.width = (this.width * 100).toFixed(2) + '%';
        this.canvas.style.height = (this.height * 100).toFixed(2) + '%';
        this.data.scale *= factor;
      } else {
        this.width *= factor;
        this.height *= factor;
        this.canvas.style.width = (this.width * 100).toFixed(2) + '%';
        this.canvas.style.height = (this.height * 100).toFixed(2) + '%';
        this.data.scale *= factor;
//        this._fit();
//        factor = this.width / w;
      }
      left = (this.left + 0.5) * factor - 0.5;
      top = (this.top + 0.5) * factor - 0.5;
      return this._offset(left, top);
    };

I do not want to make me fit, if I want to place all the full picture but focused.

**Comment by matiasgagliano** [comment]
@gshaxor you're having problems modifying the plugin itself, this really isn't an **issue** of the plugin so this discussion/question doesn't belong here. Please read the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md).

Hint: To set a max zoom, instead of modifying the plugin it's much easier to check the zoom (or scale) factor before calling the `zoomIn` function:

```javascript
  $('#zoom_in').click(function () {
    if (picture.guillotine('getData').scale > 1) return
    picture.guillotine('zoomIn');
 });  
```

If you have more questions or want to discuss it further please head over to [Guillotine's chat room](https://gitter.im/matiasgagliano/guillotine) on Gitter or to any of the resources listed in the CONTRIBUTING file.

**Comment by gshaxor** [comment]
Ok :(
But where I make the suggestion so you can remove the zoom and focus the full image (and not just a fragment)?

**Comment by matiasgagliano** [comment]
It's not very clear what you mean by "remove the zoom" but as I said go to [Guillotine's chat room](https://gitter.im/matiasgagliano/guillotine) and we can discuss it over there.
