### ISSUE TITLE
Precise crop area

### ISSUE THREAD

**Issue by nobutsta** [matiasgagliano/guillotine#48]
Hello,
I tried cropping the original image with those val sent from your plugin. But the given values seems like it's not work. Here's the spec.
- Original image size : 1920x1014
- Preview size : 1024x768
- Crop position : [x] => 592 [y] => 127 
- scale => 1.008 
- angle => 0

After I use these values to crop the image with php. The position (x,y) is not start on the correct point. I also tried change every values. But no luck. Can you please give an example of precise php to crop the image correctly?

**Comment by matiasgali** [comment]
Hi @nobutsta, this appears to be a question rather than an actual issue. Please read the [guidelines for contributing](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md).

Possibly you're not applying all the transformations (rotation and zoom) **before** cropping, as it says in the docs:

> **Important**: You should rotate and scale first, and then apply the cropping coordinates to get it right!

If that doesn't solve your problem use any of the resources listed in the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md) to get help. Let's keep the issue tracker only to report issues or bugs.

**Comment by neo125874** [comment]
@matiasgagliano thanks for your plugin & info about "apply before crop" again.
