### ISSUE TITLE
Scaling Error in Safari and iOS 

### ISSUE THREAD

**Issue by niczem** [matiasgagliano/guillotine#56]
After initialzing the .guillotine-canvas has a width of 0% and doesn't change even when its zoomed.

**Comment by niczem** [comment]
... I just tested in your demosite and it worked in safari.
The problem seems to be somewhere in the way I added to my website. The weird thing is that it`s working in Chrome and Firefox. [Project Link - valid for three days](http://urlgone.com/db2e41/)

**Comment by niczem** [comment]
[New project link - valid for three days](http://urlgone.com/3c4d4a/)

**Comment by matiasgali** [comment]
Hi @niczem, please take a look at the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md).

If you found an issue provide the bare minimum code that would reproduce it to allow debugging it. If you have problems with your own implementation or have questions don't use the issue tracker, please refer to the community.

Most likely your problem is the same as in #3, you are initializing the plugin before the image gets fully loaded.

**Comment by niczem** [comment]
Sorry I didn't looked at the contributing file and just asked. So thank you very much that you helpen anyway!

**Comment by matiasgali** [comment]
If wrapping the call to the plugin in an image `onload` event, like explained in #3, doesn't fix your problem pass by [Guillotine's chat room on Gitter](https://gitter.im/matiasgagliano/guillotine) to ask about your particular issue.
